services:
  speaker_recognition:
    class: Lavulator\SpeakerRecognitionBundle\Manager\SpeakerRecognitionManager
    arguments: ['%recognition_api_endpoint%', '%ocp_apim_subscription_key_1%']
    public: true